//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//     Support: http://www.cnblogs.com/huxj
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace JiangNan.CRM.DataMap
{

    /// <summary>
    /// 实体类CallBackLog 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Serializable]
    public partial class CallBackLog : Entity
    {
        public CallBackLog() : base("CRM_CallBackLog") { }

        #region Model
        private int _Id;
        private int _CustomerId;
        private DateTime? _CallBackDate;
        private int? _CallBackType;
        private string _CallBackDetail;
        private int? _CollegeNo;
        private int? _LevelNo;
        private int? _MajorNo;
        private string _ChooseOtherCollegeReason;
        private DateTime? _ExpectApplyDate;
        private DateTime? _ExpectVisitDate;
        private DateTime? _NextCalllBackDate;
        private DateTime? _LastModifyDate;
        private string _Modifyer;
        private string _Receiver;
        private DateTime? _CreateDate;
        /// <summary>
        /// 
        /// </summary>
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange(_.Id, _Id, value);
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int CustomerId
        {
            get { return _CustomerId; }
            set
            {
                this.OnPropertyValueChange(_.CustomerId, _CustomerId, value);
                this._CustomerId = value;
            }
        }
        /// <summary>
        /// 回访日期
        /// </summary>
        public DateTime? CallBackDate
        {
            get { return _CallBackDate; }
            set
            {
                this.OnPropertyValueChange(_.CallBackDate, _CallBackDate, value);
                this._CallBackDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? CallBackType
        {
            get { return _CallBackType; }
            set
            {
                this.OnPropertyValueChange(_.CallBackType, _CallBackType, value);
                this._CallBackType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CallBackDetail
        {
            get { return _CallBackDetail; }
            set
            {
                this.OnPropertyValueChange(_.CallBackDetail, _CallBackDetail, value);
                this._CallBackDetail = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? CollegeNo
        {
            get { return _CollegeNo; }
            set
            {
                this.OnPropertyValueChange(_.CollegeNo, _CollegeNo, value);
                this._CollegeNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? LevelNo
        {
            get { return _LevelNo; }
            set
            {
                this.OnPropertyValueChange(_.LevelNo, _LevelNo, value);
                this._LevelNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? MajorNo
        {
            get { return _MajorNo; }
            set
            {
                this.OnPropertyValueChange(_.MajorNo, _MajorNo, value);
                this._MajorNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ChooseOtherCollegeReason
        {
            get { return _ChooseOtherCollegeReason; }
            set
            {
                this.OnPropertyValueChange(_.ChooseOtherCollegeReason, _ChooseOtherCollegeReason, value);
                this._ChooseOtherCollegeReason = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? ExpectApplyDate
        {
            get { return _ExpectApplyDate; }
            set
            {
                this.OnPropertyValueChange(_.ExpectApplyDate, _ExpectApplyDate, value);
                this._ExpectApplyDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? ExpectVisitDate
        {
            get { return _ExpectVisitDate; }
            set
            {
                this.OnPropertyValueChange(_.ExpectVisitDate, _ExpectVisitDate, value);
                this._ExpectVisitDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? NextCalllBackDate
        {
            get { return _NextCalllBackDate; }
            set
            {
                this.OnPropertyValueChange(_.NextCalllBackDate, _NextCalllBackDate, value);
                this._NextCalllBackDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? LastModifyDate
        {
            get { return _LastModifyDate; }
            set
            {
                this.OnPropertyValueChange(_.LastModifyDate, _LastModifyDate, value);
                this._LastModifyDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Modifyer
        {
            get { return _Modifyer; }
            set
            {
                this.OnPropertyValueChange(_.Modifyer, _Modifyer, value);
                this._Modifyer = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Receiver
        {
            get { return _Receiver; }
            set
            {
                this.OnPropertyValueChange(_.Receiver, _Receiver, value);
                this._Receiver = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? CreateDate
        {
            get { return _CreateDate; }
            set
            {
                this.OnPropertyValueChange(_.CreateDate, _CreateDate, value);
                this._CreateDate = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Id};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Id,
				_.CustomerId,
				_.CallBackDate,
				_.CallBackType,
				_.CallBackDetail,
				_.CollegeNo,
				_.LevelNo,
				_.MajorNo,
				_.ChooseOtherCollegeReason,
				_.ExpectApplyDate,
				_.ExpectVisitDate,
				_.NextCalllBackDate,
				_.LastModifyDate,
				_.Modifyer,
				_.Receiver,
				_.CreateDate};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Id,
				this._CustomerId,
				this._CallBackDate,
				this._CallBackType,
				this._CallBackDetail,
				this._CollegeNo,
				this._LevelNo,
				this._MajorNo,
				this._ChooseOtherCollegeReason,
				this._ExpectApplyDate,
				this._ExpectVisitDate,
				this._NextCalllBackDate,
				this._LastModifyDate,
				this._Modifyer,
				this._Receiver,
				this._CreateDate};
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "CRM_CallBackLog");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Id = new Field("Id", "CRM_CallBackLog", "Id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CustomerId = new Field("CustomerId", "CRM_CallBackLog", "CustomerId");
            /// <summary>
            /// 回访日期
            /// </summary>
            public readonly static Field CallBackDate = new Field("CallBackDate", "CRM_CallBackLog", "回访日期");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CallBackType = new Field("CallBackType", "CRM_CallBackLog", "CallBackType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CallBackDetail = new Field("CallBackDetail", "CRM_CallBackLog", "CallBackDetail");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CollegeNo = new Field("CollegeNo", "CRM_CallBackLog", "CollegeNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LevelNo = new Field("LevelNo", "CRM_CallBackLog", "LevelNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MajorNo = new Field("MajorNo", "CRM_CallBackLog", "MajorNo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ChooseOtherCollegeReason = new Field("ChooseOtherCollegeReason", "CRM_CallBackLog", "ChooseOtherCollegeReason");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExpectApplyDate = new Field("ExpectApplyDate", "CRM_CallBackLog", "ExpectApplyDate");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExpectVisitDate = new Field("ExpectVisitDate", "CRM_CallBackLog", "ExpectVisitDate");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field NextCalllBackDate = new Field("NextCalllBackDate", "CRM_CallBackLog", "NextCalllBackDate");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LastModifyDate = new Field("LastModifyDate", "CRM_CallBackLog", "LastModifyDate");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Modifyer = new Field("Modifyer", "CRM_CallBackLog", "Modifyer");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Receiver = new Field("Receiver", "CRM_CallBackLog", "Receiver");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CreateDate = new Field("CreateDate", "CRM_CallBackLog", "CreateDate");
        }
        #endregion


    }
}

